package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "test_setup",
    srcs = ["test_setup.cpp"],
    deps = [
        "//src/common:benchmark_utils",
        "//src/common:matrix_utils",
        "@fmt",
    ],
)
